name: Сборка APK
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build APK
        run: |
          npm install -g @capacitor/cli @capacitor/core
          npm install @capacitor/android
          npx cap init TAPATEL "com.koshel0400tech.tapatel" --web-dir=.
          npx cap add android
          npx cap sync
          cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TAPATEL-303
          path: android/app/build/outputs/apk/debug/app-debug.apk


